# Generated by Django 3.1.1 on 2020-09-05 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='idEstado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.estado'),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='idPais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.pais'),
        ),
    ]
